# Vještačka inteligencija - Vježbe 4 - Zadaća 3

## Zadatak br. 1

### Svjetska Banka želi da donese odluku o tome da li je novopredloženi projekat isplativ za realizaciju:
* Na osnovu slučajeva iz prošlosti prikazani na slici 1 treba napraviti klasifikacioni model koristeći algoritam Naivnog Bajesa.
* Istu tabelu iskoristiti i primjeniti stablo odlučivanja.
### U oba slučaja provjeriti koja će se donijeti odluka.

![alt text](Slika1.png "Slika 1")

In [76]:
# Konverzcija string podataka u numericke vrijednosti (kategorije)

from convert import convert_csv

input_csv = 'Zadatak1_RawData.csv'
output_csv = 'Zadatak1_Data.csv'

convert_csv(input_csv, output_csv)

Podaci su konvertovani i spremljeni u novi CSV


In [77]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

In [78]:
# Ucitavanje i razdvajanje na podatke i rezultate

dataset = pd.read_csv('Zadatak1_Data.csv')
podaci = dataset.iloc[:, :-1].values
rezultat = dataset.iloc[:, -1].values

print('Ucitani podaci')
print(podaci)
print('Ucitani rezultati')
print(rezultat)

Ucitani podaci
[[0 0 0 0]
 [1 1 1 0]
 [0 2 0 1]
 [1 0 1 1]
 [0 1 0 0]
 [1 2 1 0]
 [0 0 0 1]
 [1 1 1 1]
 [0 2 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [1 2 1 1]
 [0 0 0 0]
 [1 1 1 0]
 [0 2 0 1]]
Ucitani rezultati
[0 0 1 1 0 0 1 1 0 0 1 0 0 0 1]


In [79]:
# Podjela podataka i rezultata u TRAIN i TEST (25%)

podaci_train, podaci_test, rezultat_train, rezultat_test = train_test_split(podaci, rezultat, test_size = 0.25,random_state = 0)

print("Podaci TRAIN")
print(podaci_train)
print("Podaci TEST")
print(podaci_test)

print("Rezultat TRAIN")
print(rezultat_train)
print("Rezultat TEST")
print(rezultat_test)

Podaci TRAIN
[[0 2 0 1]
 [0 1 0 0]
 [0 2 0 1]
 [1 1 1 0]
 [0 1 0 1]
 [1 1 1 1]
 [1 2 1 1]
 [1 0 1 1]
 [0 0 0 0]
 [1 2 1 0]
 [0 0 0 0]]
Podaci TEST
[[1 1 1 0]
 [0 0 0 1]
 [0 2 0 0]
 [1 0 1 0]]
Rezultat TRAIN
[1 0 1 0 1 1 0 1 0 0 0]
Rezultat TEST
[0 1 0 0]


In [80]:
# Skaliranje i transformacija TRAIN i TEST podataka

sc = StandardScaler()
podaci_train = sc.fit_transform(podaci_train)
podaci_test = sc.transform(podaci_test)

print("Transformisani Podaci TRAIN")
print(podaci_train)
print("Transformisani Podaci TEST")
print(podaci_test)

Transformisani Podaci TRAIN
[[-0.91287093  1.14707867 -0.91287093  0.91287093]
 [-0.91287093 -0.11470787 -0.91287093 -1.09544512]
 [-0.91287093  1.14707867 -0.91287093  0.91287093]
 [ 1.09544512 -0.11470787  1.09544512 -1.09544512]
 [-0.91287093 -0.11470787 -0.91287093  0.91287093]
 [ 1.09544512 -0.11470787  1.09544512  0.91287093]
 [ 1.09544512  1.14707867  1.09544512  0.91287093]
 [ 1.09544512 -1.3764944   1.09544512  0.91287093]
 [-0.91287093 -1.3764944  -0.91287093 -1.09544512]
 [ 1.09544512  1.14707867  1.09544512 -1.09544512]
 [-0.91287093 -1.3764944  -0.91287093 -1.09544512]]
Transformisani Podaci TEST
[[ 1.09544512 -0.11470787  1.09544512 -1.09544512]
 [-0.91287093 -1.3764944  -0.91287093  0.91287093]
 [-0.91287093  1.14707867 -0.91287093 -1.09544512]
 [ 1.09544512 -1.3764944   1.09544512 -1.09544512]]


### Decision Tree

In [81]:
# Treniranje i predikcija rezultata za Decision Tree

classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(podaci_train, rezultat_train)

rezultat_predict = classifier.predict(podaci_test)
print("Predvidjanje rezultata")
print(np.concatenate((rezultat_predict.reshape(len(rezultat_predict), 1), rezultat_test.reshape(len(rezultat_test), 1)), 1))

cm = confusion_matrix(rezultat_test, rezultat_predict)
print("Konfuzijska matrica")
print(cm)

ac = accuracy_score(rezultat_test, rezultat_predict)
print("Preziznost")
print(ac)

Predvidjanje rezultata
[[0 0]
 [1 1]
 [0 0]
 [0 0]]
Konfuzijska matrica
[[3 0]
 [0 1]]
Preziznost
1.0


### Naive Bayes

In [82]:
# Treniranje i predikcija rezultata za Naive Bayes

classifier = GaussianNB()
classifier.fit(podaci_train, rezultat_train)

rezultat_predict = classifier.predict(podaci_test)
print("Predvidjanje rezultata")
print(np.concatenate((rezultat_predict.reshape(len(rezultat_predict), 1), rezultat_test.reshape(len(rezultat_test), 1)), 1))

cm = confusion_matrix(rezultat_test, rezultat_predict)
print("Konfuzijska matrica")
print(cm)

ac = accuracy_score(rezultat_test, rezultat_predict)
print("Preziznost")
print(ac)

Predvidjanje rezultata
[[0 0]
 [1 1]
 [0 0]
 [0 0]]
Konfuzijska matrica
[[3 0]
 [0 1]]
Preziznost
1.0


## Zadatak br. 2

### Suad je u dilemi. Treba da stigne do fakulteta na vježbe iz "Vještačke inteligencije", ali kako je saobraćaj u Sarajevu nepredvidiv, često mu se dogodi da kasni. Kako bi izbjegao kašnjenje, pokušaće da koristi znanje iz prošlosti da predvidi da li treba da krene ranije nego obično. Napisao je situacije iz prošlosti prikazane na slici 2.
* Napravite drvo odlučivanja koje će Suadu pomoći u donošenju odluke.
* Napravite Naive Bayes model koje će Suadu pomoći u donošenju odluke.
### U oba slučaja provjeriti koja će se donijeti odluka.

![alt text](Slika2.png "Slika 2")

In [83]:
# Konverzcija string podataka u numericke vrijednosti (kategorije)

input_csv = 'Zadatak2_RawData.csv'
output_csv = 'Zadatak2_Data.csv'

convert_csv(input_csv, output_csv)

Podaci su konvertovani i spremljeni u novi CSV


In [84]:
# Ucitavanje i razdvajanje na podatke i rezultate

dataset = pd.read_csv('Zadatak2_Data.csv')
podaci = dataset.iloc[:, :-1].values
rezultat = dataset.iloc[:, -1].values

print('Ucitani podaci')
print(podaci)
print('Ucitani rezultati')
print(rezultat)

Ucitani podaci
[[0 0 0]
 [1 1 1]
 [2 1 2]
 [3 0 2]
 [4 0 0]
 [5 1 2]
 [6 0 1]
 [0 0 0]
 [1 1 2]
 [5 1 1]
 [2 1 0]
 [4 0 2]
 [3 0 1]
 [0 0 0]
 [1 0 2]
 [6 1 2]
 [1 0 2]]
Ucitani rezultati
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 2 2]


In [85]:
# Podjela podataka i rezultata u TRAIN i TEST (25%)

podaci_train, podaci_test, rezultat_train, rezultat_test = train_test_split(podaci, rezultat, test_size = 0.25,random_state = 0)

print("Podaci TRAIN")
print(podaci_train)
print("Podaci TEST")
print(podaci_test)

print("Rezultat TRAIN")
print(rezultat_train)
print("Rezultat TEST")
print(rezultat_test)

Podaci TRAIN
[[4 0 0]
 [2 1 2]
 [1 0 2]
 [2 1 0]
 [0 0 0]
 [1 0 2]
 [4 0 2]
 [3 0 2]
 [0 0 0]
 [5 1 2]
 [6 1 2]
 [3 0 1]]
Podaci TEST
[[1 1 1]
 [6 0 1]
 [1 1 2]
 [5 1 1]
 [0 0 0]]
Rezultat TRAIN
[1 2 2 1 1 2 2 0 0 2 2 0]
Rezultat TEST
[1 0 2 0 1]


In [86]:
# Skaliranje i transformacija TRAIN i TEST podataka

sc = StandardScaler()
podaci_train = sc.fit_transform(podaci_train)
podaci_test = sc.transform(podaci_test)

print("Transformisani Podaci TRAIN")
print(podaci_train)
print("Transformisani Podaci TEST")
print(podaci_test)

Transformisani Podaci TRAIN
[[ 0.76719926 -0.70710678 -1.35250445]
 [-0.31590558  1.41421356  0.81150267]
 [-0.857458   -0.70710678  0.81150267]
 [-0.31590558  1.41421356 -1.35250445]
 [-1.39901042 -0.70710678 -1.35250445]
 [-0.857458   -0.70710678  0.81150267]
 [ 0.76719926 -0.70710678  0.81150267]
 [ 0.22564684 -0.70710678  0.81150267]
 [-1.39901042 -0.70710678 -1.35250445]
 [ 1.30875168  1.41421356  0.81150267]
 [ 1.8503041   1.41421356  0.81150267]
 [ 0.22564684 -0.70710678 -0.27050089]]
Transformisani Podaci TEST
[[-0.857458    1.41421356 -0.27050089]
 [ 1.8503041  -0.70710678 -0.27050089]
 [-0.857458    1.41421356  0.81150267]
 [ 1.30875168  1.41421356 -0.27050089]
 [-1.39901042 -0.70710678 -1.35250445]]


### Decision Tree

In [87]:
# Treniranje i predikcija rezultata za Decision Tree

classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(podaci_train, rezultat_train)

rezultat_predict = classifier.predict(podaci_test)
print("Predvidjanje rezultata")
print(np.concatenate((rezultat_predict.reshape(len(rezultat_predict), 1), rezultat_test.reshape(len(rezultat_test), 1)), 1))

cm = confusion_matrix(rezultat_test, rezultat_predict)
print("Konfuzijska matrica")
print(cm)

ac = accuracy_score(rezultat_test, rezultat_predict)
print("Preziznost")
print(ac)

Predvidjanje rezultata
[[0 1]
 [0 0]
 [2 2]
 [0 0]
 [0 1]]
Konfuzijska matrica
[[2 0 0]
 [2 0 0]
 [0 0 1]]
Preziznost
0.6


### Naive Bayes

In [88]:
# Treniranje i predikcija rezultata za Naive Bayes

classifier = GaussianNB()
classifier.fit(podaci_train, rezultat_train)

rezultat_predict = classifier.predict(podaci_test)
print("Predvidjanje rezultata")
print(np.concatenate((rezultat_predict.reshape(len(rezultat_predict), 1), rezultat_test.reshape(len(rezultat_test), 1)), 1))

cm = confusion_matrix(rezultat_test, rezultat_predict)
print("Konfuzijska matrica")
print(cm)

ac = accuracy_score(rezultat_test, rezultat_predict)
print("Preziznost")
print(ac)

Predvidjanje rezultata
[[2 1]
 [0 0]
 [2 2]
 [2 0]
 [1 1]]
Konfuzijska matrica
[[1 0 1]
 [0 1 1]
 [0 0 1]]
Preziznost
0.6
